const VOTE = "VOTE";
const JOIN = "JOIN";
const LEAVE = "LEAVE";
const CLEAR_VOTES = "CLEAR_VOTES";
const REVEAL_VOTES = "REVEAL_VOTES";
const HIDE_VOTES = "HIDE_VOTES";
const UPDATE_STATE = "UPDATE_STATE";

export {
  VOTE,
  JOIN,
  LEAVE,
  CLEAR_VOTES,
  REVEAL_VOTES,
  HIDE_VOTES,
  UPDATE_STATE,
};
